### ISSUE TITLE
Feature Request:  Lock Vertical

### ISSUE THREAD

**Issue by whogben** [Goutte/godot-trackball-camera#1]
Hi Goutte, thanks for making this add-on!

Is it possible to configure the add-on in order to keep the horizon horizontal?

**Comment by Goutte** [comment]
Hi !  You're welcome :)

I did not see the notification for this issue ; sorry.

Keeping the horizon horizontal can be done a number of ways.  ~~The simplest I can fathom is by not using quaternions as we do, but instead using a spherical coordinates system.~~

It would be nice if this trackball camera had both behaviors.

I'll think about it.  It's probably also a good first pick for anyone interested.  I could not find at first glance a spherical => cartesian function in Godot, but the web is vast.

**Comment by Goutte** [comment]
No need for all that.  I'd forgotten how the quats were built.

Version 5.0 will have a `stabilize_horizon` boolean exported parameter. ;) @whogben :hourglass: :pray:
