### ISSUE TITLE
Middle Mouse Wheel seems to not zoom even when zoom is checked.

### ISSUE THREAD

**Issue by BracerJack** [Goutte/godot-trackball-camera#10]
Middle Mouse Wheel seems to not zoom even when zoom is checked.
Using Godot 3.3.2

**Comment by BracerJack** [comment]
[Shader Test.zip](https://github.com/Goutte/godot-trackball-camera/files/6779823/Shader.Test.zip)

**Comment by Goutte** [comment]
There is no default action for mouse wheel, so the camera is not bound to the mouse wheel by default, you have to make your own `cam_zoom_in` action and then configure the camera to use it.

Perhaps we could have the plugin add the action itself when loaded, for convenience.  I'm not sure if it can be done.

**Comment by BracerJack** [comment]
Oh thank you for your reply.
Don't worry about it, I just "took for granted" that the middle mouse is zoom because of all the 3D programs I am using, you are right, your description did not in anyway say that by checking the zoom checkbox, the wheel will be the zoom, the fault is with me. Thanks for replying :D
I will close the issue now.
