### ISSUE TITLE
Problem with zoom actions

### ISSUE THREAD

**Issue by jospic** [Goutte/godot-trackball-camera#11]
Hi, 
page_up and page_down actions cause the same behavior: an uncontrolled zoom out, without the possibility of restoring the original view.
Any suggestions?
Thanks in advance.
-j

**Comment by Goutte** [comment]
Oh my !

We tweaked the zoom values lately, perhaps we introduced a bug ?

Did you tweak the camera config ?  Did you use this repository directly, or the addon from the "marketplace" ?

**Comment by jospic** [comment]
Hi,
I'm installed official version from Godot assetlib.

**Comment by jospic** [comment]
Sorry, I'm wrong. 
It seems that the problem occurs if the camera's parent node is not a mesh but a spatial node.
I try to understand something more.
-j

**Comment by Goutte** [comment]
@jospic Is there a `scale` in the parent node ?  Or the camera ?

**Comment by jospic** [comment]
Yes there is a scale in the parent.

Il ven 30 lug 2021, 13:18 Antoine Goutenoir ***@***.***> ha
scritto:

**Comment by Goutte** [comment]
Did you figure it out ?   If anyone else encounters this bug, please send me instructions to reproduce it.

**Comment by Goutte** [comment]
Please reopen if it happens again.
