### ISSUE TITLE
Is there a way to make it match the mouse movement exactly and not do the acceleration-deceleration thing ? Like Blender/3DS Max/Maya/Lightwave ?

### ISSUE THREAD

**Issue by BracerJack** [Goutte/godot-trackball-camera#17]
Is there a way to make it match the mouse movement exactly and not do the acceleration-deceleration thing ? Like Blender/3DS Max/Maya/Lightwave ?

Its current implementation give me motion sickness, when I let go of the mouse I would like it to stop immediately, and when I start the rotation, may I request that it doesn't "pick up speed" but get straight to the actual speed of the mouse like a normal 3D modeling program ? Thanks :D

**Comment by Goutte** [comment]
That's a great idea !

Perhaps we can handle a `disable_inertia` parameter.   We may or may not need a significant rewrite, not sure ; feel free to bounty the issue to boost it, as I'm currently looking for a job (and money). :fox_face:

**Comment by Goutte** [comment]
I might get a job soon, so to celebrate I took some time to pump up this plugin for Godot `4`.

Along the way, I added a `no_drag_inertia` parameter to the Godot 4 version, in #18 

No more motion sickness !
