### ISSUE TITLE
Invalid get index 'silent' (on base: 'Camera3D (trackball_camera.gd)').

### ISSUE THREAD

**Issue by chrisl8** [Goutte/godot-trackball-camera#27]
When I use this I get the error:

`Invalid get index 'silent' (on base: 'Camera3D (trackball_camera.gd)').`

against line 632 of `trackball_camera.gd`:
[        if not self.silent:](https://github.com/Goutte/godot-trackball-camera/blob/194be1606289ea5457332ea0720a1ace69b1744a/addons/goutte.camera.trackball/trackball_camera.gd#L632)

Commenting out that line allows it to work though.

This is using Godot v4.1.1.stable.official [bd6af8e0e]

**Comment by Goutte** [comment]
Well spotted !   I got mixed up in the refacto, it appears.

Weird that I did not spot it after publication…

Anyway, thanks !

The fix is trivial, just remove the `self.` in `self.silent`, as you figured out.

---

Will fix asap.

**Comment by Goutte** [comment]
I also (in emergency) updated the publication of the asset in the store here : https://godotengine.org/asset-library/asset/1832

Sorry for the long response time, I spent most of the past months in the hospital, without internet access. (they'd been breached) :hospital: :mask: 

And thanks again for taking the time to report this !  :heart:
