### ISSUE TITLE
action_strength less than or equal to 0.1

### ISSUE THREAD

**Issue by bmolyneaux** [Goutte/godot-trackball-camera#9]
Setting action_strength to 0.1 makes keyboard rotation flaky and setting it below 0.1 prevents keyboard rotation. This is problematic because 0.1 is a reasonable value here.

Perhaps either the _epsilon variable should be exported, there should be a warning if action_strength is less than or equal to 0.1, or epsilon should be decreased.

**Comment by Goutte** [comment]
Thanks !

I had wondered whether to make the _inertiaTreshold (epsilon) an exported variable or not.

Of course, I should have.

I won't have time to handle this until next year ; if anyone want to take this on, go for it !
